# -*- coding: utf-8 -*-
"""Pneumonia_ViT_1200_train_test_pgd_diffeps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Afwlk-HLsTkl_dDUA9s0IUUHNFnz1_2y

https://github.com/akmmes/Medical-Image-Classification-using-Vision-Transformers-for-CT-and-X-ray-Images
"""

import tensorflow as tf
from tensorflow.python.keras import backend as K

# adjust values to your needs
config = tf.compat.v1.ConfigProto( device_count = {'GPU': 1 , 'CPU': 8} )
sess = tf.compat.v1.Session(config=config)
K.set_session(sess)

import numpy as np # linear algebra
import cv2 # import cv2
from PIL import Image

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/Research_workarea/xray_pneumonia/xray_pneumonia.zip

import os
import cv2

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.metrics as metrics

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

#from keras.utils import np_utils

from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16, ResNet101, Xception
from tensorflow.keras.layers import Input, Dense, Flatten, MaxPooling2D, GlobalAveragePooling2D, Dropout, BatchNormalization, Conv2D, InputLayer

from tensorflow.keras.models import Model, load_model

# LR = 0.0001
EPOCHS = 500
BATCH_SIZE = 16
IMG_SIZE = 224

train_folder = '/content/xray_pneumonia/train'
test_folder ='/content/xray_pneumonia/test'
val_folder ='/content/xray_pneumonia/val'

labels = ["NORMAL", "PNEUMONIA"] # each folder has two sub folder name "PNEUMONIA", "NORMAL"
IMG_SIZE = 224 # resize image

def get_data_train(data_dir):
    data = []

    for label in labels:
        count = 0
        path = os.path.join(data_dir, label)
        class_num = labels.index(label)
        for img in os.listdir(path):
            try:
                count = count + 1
                if(count > 480):
                  break

                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                data.append([new_array, class_num])
            except Exception as e:
                print(e)
    return np.array(data)

def get_data_test(data_dir):
    data = []

    for label in labels:
        count = 0
        path = os.path.join(data_dir, label)
        class_num = labels.index(label)
        for img in os.listdir(path):
            try:
                count = count + 1
                if(count > 120):
                  break

                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                data.append([new_array, class_num])
            except Exception as e:
                print(e)
    return np.array(data)

import os
train = get_data_train(train_folder)
test = get_data_test(test_folder)
val = get_data_train(val_folder)

X_train = []
y_train = []

X_val = []
y_val = []

X_test = []
y_test = []

for feature, label in train:
    X_train.append(feature)
    y_train.append(label)

for feature, label in test:
    X_test.append(feature)
    y_test.append(label)

for feature, label in val:
    X_val.append(feature)
    y_val.append(label)

print(X_train[1])

from collections import Counter
print(Counter(y_train))
print(Counter(y_test))

X_train = np.array(X_train)/255
y_train = np.array(y_train)
X_test = np.array(X_test)/255
y_test= np.array(y_test)
X_val = np.array(X_val)/255
y_val = np.array(y_val)

from keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_val = to_categorical(y_val)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
print(X_val.shape)
print(y_val.shape)

def expand_greyscale_image_channels(grey_image):
    grey_image_arr = np.array(grey_image)
    grey_image_arr = np.expand_dims(grey_image_arr, -1)
    grey_image_arr_3_channel = grey_image_arr.repeat(3, axis=-1)
    return grey_image_arr_3_channel

print(X_train[1].shape)

print(X_train.shape)

X_train1 = []
for i in range(len(X_train)):
  X_train1.append(expand_greyscale_image_channels(X_train[i]))

print(np.array(X_train1[1]).shape)

X_test1 = []
for i in range(len(X_test)):
  X_test1.append(expand_greyscale_image_channels(X_test[i]))

X_train = np.array(X_train1)
X_test = np.array(X_test1)
print(X_train.shape)
print(X_test.shape)

# !pip install --user tensorflow-addons==0.8.3
# !pip install --user tensorflow==2.2.0-rc3

!pip install tensorflow-addons

import pandas as pd
import numpy as np
import tensorflow as tf
import tensorflow_addons as tfa
import glob, warnings
import matplotlib.pyplot as plt
import pathlib
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

warnings.filterwarnings('ignore')
print('TensorFlow Version ' + tf.__version__)

!pip install --quiet vit-keras

from vit_keras import vit

vit_model = vit.vit_b32(
        image_size = 224,
        activation = 'softmax',
        pretrained = True,
        include_top = False,
        pretrained_top = False,
        classes = 2)


# # image_size = 224
# vit_model = vit.vit_l32(
#     image_size=224,
#     activation='softmax',
#     pretrained=True,
#     include_top=True,
#     pretrained_top=False,
#     classes=2
# )

model = tf.keras.Sequential([
        vit_model,
        tf.keras.layers.Flatten(),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(11, activation = tfa.activations.gelu),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(2, 'softmax')
    ],
    name = 'vision_transformer')

model.summary()

train_aug = ImageDataGenerator(rotation_range=15)

import time
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris

earlystopping = tf.keras.callbacks.EarlyStopping(monitor = 'val_accuracy',
                                                 min_delta = 1e-4,
                                                 patience = 30,
                                                 mode = 'max',
                                                 restore_best_weights = True,
                                                 verbose = 1)

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor = 'val_accuracy',
                                                 factor = 0.2,
                                                 patience = 2,
                                                 verbose = 1,
                                                 min_delta = 1e-4,
                                                 min_lr = 1e-6,
                                                 mode = 'max')

callbacks = [earlystopping, reduce_lr]
# callbacks = [reduce_lr]

# import torch
# # optim = Adam(lr = LR, decay = LR/EPOCHS)

# learning_rate = 1e-4

# # optimizer = tfa.optimizers.AdamW(learning_rate = learning_rate)

# optimizer = tfa.optimizers.RectifiedAdam(learning_rate = learning_rate)

# # optimizer = tfa.optimizers.AdamW(
# #     learning_rate=1e-4,
# #     weight_decay=1e-4
# # )
# # optimizer = opt

# # model.compile(optimizer = optimizer,
# #               loss = tf.keras.losses.BinaryCrossentropy(label_smoothing = 0.2),
# #               metrics = ['accuracy'])


# model.compile(optimizer = optimizer,
#               loss ='categorical_crossentropy',
#               metrics = ['accuracy'])

# # start = time.time()
# # # model.fit(X, y)
# # stop = time.time()
# # print(f"Training time: {stop - start}s")

# import time
# start = time.time()

# # model.compile(loss='categorical_crossentropy', optimizer=optim, metrics=['accuracy'])

# # compile the model with precision, recall, and F1 score as metrics
# # model.compile(optimizer=optim, loss='categorical_crossentropy',
#               # metrics=['accuracy', keras.metrics.Precision(), keras.metrics.Recall(), keras.metrics.F1Score()])



# history = model.fit_generator(train_aug.flow(X_train, y_train, batch_size=BATCH_SIZE),
#                                     steps_per_epoch=len(X_train)//BATCH_SIZE,
#                                     validation_data=(X_test, y_test),
#                                     validation_steps=len(X_test)//BATCH_SIZE,
#                                     epochs=500,
#                                     callbacks = callbacks,
#                                     verbose=1)
# end = time.time()

# print('Program processed ', end - start, 's, ', (end - start)/60, 'min, ', (end - start)/3600, 'h')

# # stop = time.time()
# # print(f"Training time: {stop - start}s")

# model.save('/content/drive/MyDrive/Research_workarea/xray_pneumonia/keras_vit_models/vit1200_3oct.tf')

# score = model.evaluate(X_train, y_train)
# print("Model accuracy on Train dataset: %f." %(score[1]*100))

# score = model.evaluate(X_test, y_test)
# print("Model accuracy on Test dataset: %f." %(score[1]*100))

from tensorflow.keras.models import load_model
model=load_model("/content/drive/MyDrive/Research_workarea/xray_pneumonia/keras_vit_models/vit1200_3oct.tf")

score = model.evaluate(X_train, y_train)
print("Model accuracy on Train dataset: %f." %(score[1]*100))

score = model.evaluate(X_test, y_test)
print("Model accuracy on Test dataset: %f." %(score[1]*100))

y_pred = model.predict(X_test)
print(y_pred)
print(y_pred[0])
print(y_pred[0][1])

X_test_filtered=[]
y_test_original=[]
image_probs_orig=[]

count = 0
for i in range(len(y_pred)):
  if(y_pred[i][0]>=0.1 and y_pred[i][0]<=0.9 and count<130):
    print(i,":",y_pred[i])
    X_test_filtered.append(np.array(X_test[i]))
    y_test_original.append(y_test[i])
    image_probs_orig.append(y_pred[i])
    count = count + 1
print("count : ", count)

model.evaluate(X_test, np.array(y_test))

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def argmax(array):
  index, value = 0, array[0]
  for i,v in enumerate(array):
    if v > value:
      index, value = i,v
  return index

iterations = 7
alpha = 2

epsilon = 1/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,3)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,3)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

epsilon = 2/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,3)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,3)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

epsilon = 3/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,3)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,3)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

epsilon = 4/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,3)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,3)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

epsilon = 5/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,3)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,3)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))