# -*- coding: utf-8 -*-
"""Pneumonia_model4_clahe_11may_diffeps_better_results.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eAFXFs0axSmnlgcO_c0s3dBnrRGMo6vy
"""

import numpy as np # linear algebra
import cv2 # import cv2
from PIL import Image

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/Research_workarea/xray_pneumonia/xray_pneumonia.zip

DIR = open('/content/xray_pneumonia','r')
print(DIR)

train_folder = '/content/xray_pneumonia/train'
test_folder ='/content/xray_pneumonia/test'
val_folder ='/content/xray_pneumonia/val'

labels = ["NORMAL", "PNEUMONIA"] # each folder has two sub folder name "PNEUMONIA", "NORMAL"
IMG_SIZE = 224 # resize image

def get_data_train(data_dir):
    data = []

    for label in labels:
        count = 0
        path = os.path.join(data_dir, label)
        class_num = labels.index(label)
        for img in os.listdir(path):
            try:
                count = count + 1
                if(count > 1341):
                  break
                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                data.append([new_array, class_num])
            except Exception as e:
                print(e)
    return np.array(data)

import os
train = get_data_train(train_folder)
test = get_data_train(test_folder)
val = get_data_train(val_folder)

X_train = []
y_train = []

X_val = []
y_val = []

X_test = []
y_test = []

for feature, label in train:
    X_train.append(feature)
    y_train.append(label)

for feature, label in test:
    X_test.append(feature)
    y_test.append(label)

for feature, label in val:
    X_val.append(feature)
    y_val.append(label)

print(X_train[1])

# -*- coding: UTF-8 -*-
"""
"Contrast Limited Adaptive Histogram Equalization(CLAHE) implementation"
by Omer Ferhat Sarioglu, omerf.sarioglu@gmail.com
The below implementation does not assume that the
X and Y image resolutions are an integer multiple
of the X and Y sizes of the contextual regions.
Instead it pads the image with the number of excess pixels
required to make the X and Y resolutions an integral multiple
of X and Y sizes of the contextual region(if required)
Minimum and Maximum values are assumed to be 0 and 255
respectively even if they are not present in the image
"""

import numpy as np
import matplotlib.pyplot as plt
from skimage import io
from skimage import color


def image_read(im_path):
    """
    Reads image and converts it to grayscale if needed.
    :param im_path:
    :return:
    """
    try:
        image = io.imread(im_path)
        if len(image.shape) == 2:
            return image
        elif len(image.shape) == 3:
            gray_img = color.rgb2gray(image)
            return image, gray_img
        elif len(image.shape) == 4:
            gray_img = color.rgb2gray(color.rgba2rgb(image))
            return image, gray_img

    except ValueError:
        print('Error in image reading...')


def show_results(image, clahe_image, clip_size):
    """
    Shows comparison between images in subplots
    :param image:
    :param clahe_image:
    :param clip_size:
    :return:
    """
    fig, axs = plt.subplots(1, 2)
    fig.suptitle('Normal image and CLAHE implemented image comparison')
    axs[0].imshow(image, cmap='gray')
    axs[0].set_title('Normal Image\n ')
    axs[1].imshow(clahe_image, cmap='gray')
    axs[1].set_title('CLAHE Image \n Clip Sz. ={}'.format(clip_size))
    plt.show()


def interpolate(subBin, LU, RU, LB, RB, subX, subY):
    """
    Image interpolation function, need to be applied after CLAHE
    """
    subImage = np.zeros(subBin.shape)
    num = subX * subY
    for i in range(subX):
        inverseI = subX - i
        for j in range(subY):
            inverseJ = subY - j
            val = subBin[i, j].astype(int)
            subImage[i, j] = np.floor(
                (inverseI * (inverseJ * LU[val] + j * RU[val]) + i * (inverseJ * LB[val] + j * RB[val])) / float(num))
    return subImage


def clahe(img, clipLimit, nrBins=128, nrX=0, nrY=0):
    """
    CLAHE algorithm implementation
    :param img: Input image
    :param clipLimit: Normalized clipLimit. Higher value gives more contrast
    :param nrBins: Number of gray level bins for histogram("dynamic range")
    :param nrX: Number of contextual regions in X direction
    :param nrY: Number of contextual regions in Y direction
    """
    h, w = img.shape
    if clipLimit == 1:
        return
    nrBins = max(nrBins, 128)
    if nrX == 0:
        # Taking dimensions of each contextial region to be a square of 32X32
        xsz = 32
        ysz = 32
        nrX = np.ceil(h / xsz)  # 240
        # Excess number of pixels to get an integer value of nrX and nrY
        excX = int(xsz * (nrX - h / xsz))
        nrY = np.ceil(w / ysz)  # 320
        excY = int(ysz * (nrY - w / ysz))
        # Pad that number of pixels to the image
        if excX != 0:
            img = np.append(img, np.zeros((excX, img.shape[1])).astype(int), axis=0)
        if excY != 0:
            img = np.append(img, np.zeros((img.shape[0], excY)).astype(int), axis=1)
    else:
        xsz = np.round(h / nrX)
        ysz = np.round(w / nrY)
        excX = int(xsz * (nrX - h / xsz))
        excY = int(ysz * (nrY - w / ysz))
        if excX != 0:
            img = np.append(img, np.zeros((excX, img.shape[1])).astype(int), axis=0)
        if excY != 0:
            img = np.append(img, np.zeros((img.shape[0], excY)).astype(int), axis=1)

    nrPixels = xsz * ysz
    claheimg = np.zeros(img.shape)

    if clipLimit > 0:
        clipLimit = max(1, clipLimit * xsz * ysz / nrBins)
    else:
        clipLimit = 50

    # Making LUT
    print("...Make the LUT...")
    minVal = 0  # np.min(img)
    maxVal = 255  # np.max(img)

    binSz = np.floor(1 + (maxVal - minVal) / float(nrBins))
    LUT = np.floor((np.arange(minVal, maxVal + 1) - minVal) / float(binSz))

    # Creating bins from LUT with image
    bins = LUT[img]
    print(bins.shape)

    # Making Histogram
    print("...Making the Histogram...")
    nrX = int(nrX)
    nrY = int(nrY)
    xsz = int(xsz)
    ysz = int(ysz)
    hist = np.zeros((nrX, nrY, nrBins))
    print(nrX, nrY, hist.shape)
    for i in range(nrX):
        for j in range(nrY):
            bin_ = bins[i * xsz:(i + 1) * xsz, j * ysz:(j + 1) * ysz].astype(int)
            for i1 in range(xsz):
                for j1 in range(ysz):
                    hist[i, j, bin_[i1, j1]] += 1

    # Clipping Histogram
    print("...Clipping the Histogram...")
    if clipLimit > 0:
        for i in range(nrX):
            for j in range(nrY):
                nrExcess = 0
                for nr in range(nrBins):
                    excess = hist[i, j, nr] - clipLimit
                    if excess > 0:
                        nrExcess += excess

                binIncr = nrExcess / nrBins
                upper = clipLimit - binIncr
                for nr in range(nrBins):
                    if hist[i, j, nr] > clipLimit:
                        hist[i, j, nr] = clipLimit
                    else:
                        if hist[i, j, nr] > upper:
                            nrExcess += upper - hist[i, j, nr]
                            hist[i, j, nr] = clipLimit
                        else:
                            nrExcess -= binIncr
                            hist[i, j, nr] += binIncr

                if nrExcess > 0:
                    stepSz = max(1, np.floor(1 + nrExcess / nrBins))
                    for nr in range(nrBins):
                        nrExcess -= stepSz
                        hist[i, j, nr] += stepSz
                        if nrExcess < 1:
                            break

    # Mapping Histogram
    print("...Mapping the Histogram...")
    map_ = np.zeros((nrX, nrY, nrBins))
    # print(map_.shape)
    scale = (maxVal - minVal) / float(nrPixels)
    for i in range(nrX):
        for j in range(nrY):
            sum_ = 0
            for nr in range(nrBins):
                sum_ += hist[i, j, nr]
                map_[i, j, nr] = np.floor(min(minVal + sum_ * scale, maxVal))

    # Interpolation
    print("...Interpolation...")
    xI = 0
    for i in range(nrX + 1):
        if i == 0:
            subX = int(xsz / 2)
            xU = 0
            xB = 0
        elif i == nrX:
            subX = int(xsz / 2)
            xU = nrX - 1
            xB = nrX - 1
        else:
            subX = xsz
            xU = i - 1
            xB = i

        yI = 0
        for j in range(nrY + 1):
            if j == 0:
                subY = int(ysz / 2)
                yL = 0
                yR = 0
            elif j == nrY:
                subY = int(ysz / 2)
                yL = nrY - 1
                yR = nrY - 1
            else:
                subY = ysz
                yL = j - 1
                yR = j
            UL = map_[xU, yL, :]
            UR = map_[xU, yR, :]
            BL = map_[xB, yL, :]
            BR = map_[xB, yR, :]

            subBin = bins[xI:xI + subX, yI:yI + subY]

            subImage = interpolate(subBin, UL, UR, BL, BR, subX, subY)
            claheimg[xI:xI + subX, yI:yI + subY] = subImage
            yI += subY
        xI += subX

    if excX == 0 and excY != 0:
        return claheimg[:, :-excY]
    elif excX != 0 and excY == 0:
        return claheimg[:-excX, :]
    elif excX != 0 and excY != 0:
        return claheimg[:-excX, :-excY]
    else:
        return claheimg

print(X_train[0])

clip_size = 8
for i in range(len(X_train)):
  X_train[i] = clahe(X_train[i].astype(int), clip_size, 256, 4, 4)

for i in range(len(X_val)):
  X_val[i] = clahe(X_val[i].astype(int), clip_size, 256, 4, 4)

for i in range(len(X_test)):
  X_test[i] = clahe(X_test[i].astype(int), clip_size, 256, 4, 4)

X_train = np.array(X_train) / 255
X_val = np.array(X_val) / 255
X_test = np.array(X_test) / 255

print(X_test[0])

X_train = np.array(X_train).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_train = np.array(y_train)

X_val =  np.array(X_val).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_val = np.array(y_val)

X_test =  np.array(X_test).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_test = np.array(y_test)

import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.layers import Flatten, Conv2D, Activation, Dense, Dropout, MaxPooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

model = Sequential()

model.add(Conv2D(32, (3, 3), padding="same", input_shape=X_train.shape[1:]))
model.add(Activation("relu"))
model.add(MaxPooling2D(2, 2))
model.add(Dropout(0.2))

model.add(Conv2D(64, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(MaxPooling2D(2, 2))
model.add(Dropout(0.4))

model.add(Flatten())
model.add(Dense(128, activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(32, activation="relu"))
model.add(Dense(2))
model.add(Activation("sigmoid"))

model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
history = model.fit(X_train, to_categorical(np.array(y_train)), epochs=7, validation_data=(X_test, to_categorical(np.array(y_test))), shuffle=True)



import keras
#model.evaluate(X_test, to_categorical(np.array(y_test)))
#model.save("/content/drive/MyDrive/Research_workarea/xray_pneumonia/models/Pneumonia_model4_clahe.h5")
from tensorflow.keras.models import load_model
model=load_model("/content/drive/MyDrive/Research_workarea/xray_pneumonia/models/Pneumonia_model4_clahe.h5")

y_pred = model.predict(X_test)

model.evaluate(X_test, to_categorical(np.array(y_test)))

print(to_categorical(np.array(y_test)))

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

y_pred = model.predict(X_test)

model.summary()

last_conv_layer = "conv2d_14"

'''
    Function to visualize grad-cam heatmaps
    '''
gradient_model = tf.keras.models.Model(
        [model.inputs], [model.get_layer(last_conv_layer).output, model.output]
    )

# Gradient Computations
with tf.GradientTape() as tape:
    data=np.array(X_test_filtered[12])
    data=data.reshape(-1,224,224,1)
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    last_conv_layer_output, preds = gradient_model(image)

    pred_index = tf.argmax(preds[0])
    class_channel = preds[:, pred_index]

grads = tape.gradient(class_channel, last_conv_layer_output)
pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
last_conv_layer_output = last_conv_layer_output[0]
heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
heatmap = tf.squeeze(heatmap)
heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap) # Normalize the heatmap

# -*- coding: UTF-8 -*-
"""
"Contrast Limited Adaptive Histogram Equalization(CLAHE) implementation"
by Omer Ferhat Sarioglu, omerf.sarioglu@gmail.com
The below implementation does not assume that the
X and Y image resolutions are an integer multiple
of the X and Y sizes of the contextual regions.
Instead it pads the image with the number of excess pixels
required to make the X and Y resolutions an integral multiple
of X and Y sizes of the contextual region(if required)
Minimum and Maximum values are assumed to be 0 and 255
respectively even if they are not present in the image
"""

import numpy as np
import matplotlib.pyplot as plt
from skimage import io
from skimage import color


def image_read(im_path):
    """
    Reads image and converts it to grayscale if needed.
    :param im_path:
    :return:
    """
    try:
        image = io.imread(im_path)
        if len(image.shape) == 2:
            return image
        elif len(image.shape) == 3:
            gray_img = color.rgb2gray(image)
            return image, gray_img
        elif len(image.shape) == 4:
            gray_img = color.rgb2gray(color.rgba2rgb(image))
            return image, gray_img

    except ValueError:
        print('Error in image reading...')


def show_results(image, clahe_image, clip_size):
    """
    Shows comparison between images in subplots
    :param image:
    :param clahe_image:
    :param clip_size:
    :return:
    """
    fig, axs = plt.subplots(1, 2)
    fig.suptitle('Normal image and CLAHE implemented image comparison')
    axs[0].imshow(image, cmap='gray')
    axs[0].set_title('Normal Image\n ')
    axs[1].imshow(clahe_image, cmap='gray')
    axs[1].set_title('CLAHE Image \n Clip Sz. ={}'.format(clip_size))
    plt.show()


def interpolate(subBin, LU, RU, LB, RB, subX, subY):
    """
    Image interpolation function, need to be applied after CLAHE
    """
    subImage = np.zeros(subBin.shape)
    num = subX * subY
    for i in range(subX):
        inverseI = subX - i
        for j in range(subY):
            inverseJ = subY - j
            val = subBin[i, j].astype(int)
            subImage[i, j] = np.floor(
                (inverseI * (inverseJ * LU[val] + j * RU[val]) + i * (inverseJ * LB[val] + j * RB[val])) / float(num))
    return subImage


def clahe(img, clipLimit, nrBins=128, nrX=0, nrY=0):
    """
    CLAHE algorithm implementation
    :param img: Input image
    :param clipLimit: Normalized clipLimit. Higher value gives more contrast
    :param nrBins: Number of gray level bins for histogram("dynamic range")
    :param nrX: Number of contextual regions in X direction
    :param nrY: Number of contextual regions in Y direction
    """
    h, w = img.shape
    if clipLimit == 1:
        return
    nrBins = max(nrBins, 128)
    if nrX == 0:
        # Taking dimensions of each contextial region to be a square of 32X32
        xsz = 32
        ysz = 32
        nrX = np.ceil(h / xsz)  # 240
        # Excess number of pixels to get an integer value of nrX and nrY
        excX = int(xsz * (nrX - h / xsz))
        nrY = np.ceil(w / ysz)  # 320
        excY = int(ysz * (nrY - w / ysz))
        # Pad that number of pixels to the image
        if excX != 0:
            img = np.append(img, np.zeros((excX, img.shape[1])).astype(int), axis=0)
        if excY != 0:
            img = np.append(img, np.zeros((img.shape[0], excY)).astype(int), axis=1)
    else:
        xsz = np.round(h / nrX)
        ysz = np.round(w / nrY)
        excX = int(xsz * (nrX - h / xsz))
        excY = int(ysz * (nrY - w / ysz))
        if excX != 0:
            img = np.append(img, np.zeros((excX, img.shape[1])).astype(int), axis=0)
        if excY != 0:
            img = np.append(img, np.zeros((img.shape[0], excY)).astype(int), axis=1)

    nrPixels = xsz * ysz
    claheimg = np.zeros(img.shape)

    if clipLimit > 0:
        clipLimit = max(1, clipLimit * xsz * ysz / nrBins)
    else:
        clipLimit = 50

    # Making LUT
    print("...Make the LUT...")
    minVal = 0  # np.min(img)
    maxVal = 255  # np.max(img)

    binSz = np.floor(1 + (maxVal - minVal) / float(nrBins))
    LUT = np.floor((np.arange(minVal, maxVal + 1) - minVal) / float(binSz))

    # Creating bins from LUT with image
    bins = LUT[img]
    print(bins.shape)

    # Making Histogram
    print("...Making the Histogram...")
    nrX = int(nrX)
    nrY = int(nrY)
    xsz = int(xsz)
    ysz = int(ysz)
    hist = np.zeros((nrX, nrY, nrBins))
    print(nrX, nrY, hist.shape)
    for i in range(nrX):
        for j in range(nrY):
            bin_ = bins[i * xsz:(i + 1) * xsz, j * ysz:(j + 1) * ysz].astype(int)
            for i1 in range(xsz):
                for j1 in range(ysz):
                    hist[i, j, bin_[i1, j1]] += 1

    # Clipping Histogram
    print("...Clipping the Histogram...")
    if clipLimit > 0:
        for i in range(nrX):
            for j in range(nrY):
                nrExcess = 0
                for nr in range(nrBins):
                    excess = hist[i, j, nr] - clipLimit
                    if excess > 0:
                        nrExcess += excess

                binIncr = nrExcess / nrBins
                upper = clipLimit - binIncr
                for nr in range(nrBins):
                    if hist[i, j, nr] > clipLimit:
                        hist[i, j, nr] = clipLimit
                    else:
                        if hist[i, j, nr] > upper:
                            nrExcess += upper - hist[i, j, nr]
                            hist[i, j, nr] = clipLimit
                        else:
                            nrExcess -= binIncr
                            hist[i, j, nr] += binIncr

                if nrExcess > 0:
                    stepSz = max(1, np.floor(1 + nrExcess / nrBins))
                    for nr in range(nrBins):
                        nrExcess -= stepSz
                        hist[i, j, nr] += stepSz
                        if nrExcess < 1:
                            break

    # Mapping Histogram
    print("...Mapping the Histogram...")
    map_ = np.zeros((nrX, nrY, nrBins))
    # print(map_.shape)
    scale = (maxVal - minVal) / float(nrPixels)
    for i in range(nrX):
        for j in range(nrY):
            sum_ = 0
            for nr in range(nrBins):
                sum_ += hist[i, j, nr]
                map_[i, j, nr] = np.floor(min(minVal + sum_ * scale, maxVal))

    # Interpolation
    print("...Interpolation...")
    xI = 0
    for i in range(nrX + 1):
        if i == 0:
            subX = int(xsz / 2)
            xU = 0
            xB = 0
        elif i == nrX:
            subX = int(xsz / 2)
            xU = nrX - 1
            xB = nrX - 1
        else:
            subX = xsz
            xU = i - 1
            xB = i

        yI = 0
        for j in range(nrY + 1):
            if j == 0:
                subY = int(ysz / 2)
                yL = 0
                yR = 0
            elif j == nrY:
                subY = int(ysz / 2)
                yL = nrY - 1
                yR = nrY - 1
            else:
                subY = ysz
                yL = j - 1
                yR = j
            UL = map_[xU, yL, :]
            UR = map_[xU, yR, :]
            BL = map_[xB, yL, :]
            BR = map_[xB, yR, :]

            subBin = bins[xI:xI + subX, yI:yI + subY]

            subImage = interpolate(subBin, UL, UR, BL, BR, subX, subY)
            claheimg[xI:xI + subX, yI:yI + subY] = subImage
            yI += subY
        xI += subX

    if excX == 0 and excY != 0:
        return claheimg[:, :-excY]
    elif excX != 0 and excY == 0:
        return claheimg[:-excX, :]
    elif excX != 0 and excY != 0:
        return claheimg[:-excX, :-excY]
    else:
        return claheimg

print(X_test[10].shape)

clip_size = 8
print(X_test[200])
gray_image = X_test[200]
gray_img = gray_image.reshape(224,224)
print(gray_img)
print(gray_img.shape)
gray_img = gray_img* 255
print("gray_img after multiplying: " , gray_img )
gray_img = gray_img.astype(int)
print("gray_img after converting to int: " , gray_img )
clahe_image = clahe(gray_img, clip_size, 256, 4, 4)

show_results(gray_img, clahe_image, clip_size)

X_test_filtered=[]
y_test_original=[]
image_probs_orig=[]

count = 0
for i in range(len(y_pred)):
  if(y_pred[i][0]>=0.1 and y_pred[i][0]<=0.9 and count < 44):
    print(i,":",y_pred[i])
    X_test_filtered.append(np.array(X_test[i]))
    y_test_original.append(y_test[i])
    image_probs_orig.append(y_pred[i])
    count = count + 1
print("count : ", count)

model.evaluate(X_test, to_categorical(np.array(y_test)))

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def argmax(array):
  index, value = 0, array[0]
  for i,v in enumerate(array):
    if v > value:
      index, value = i,v
  return index

'''
    Function to visualize grad-cam heatmaps
    '''
gradient_model = tf.keras.models.Model(
        [model.inputs], [model.get_layer(last_conv_layer).output, model.output]
    )

# Gradient Computations
with tf.GradientTape() as tape:
    data=np.array(X_test_filtered[12])
    data=data.reshape(-1,224,224,1)
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    last_conv_layer_output, preds = gradient_model(image)

    pred_index = tf.argmax(preds[0])
    class_channel = preds[:, pred_index]

grads = tape.gradient(class_channel, last_conv_layer_output)
pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
last_conv_layer_output = last_conv_layer_output[0]
heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
heatmap = tf.squeeze(heatmap)
heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap) # Normalize the heatmap

plt.matshow(heatmap.numpy())
plt.show()

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.001]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

print(image_probs_adv1)

print(len(image_probs_orig))
print(len(image_probs_adv1))

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))
print(abspred)

np.sum(abspred,axis=0)

#epsilon = 0.002


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.002]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.003


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.003]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.004


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.004]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.005


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.005]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.006


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.006]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

model.save("/content/drive/MyDrive/Research_workarea/xray_pneumonia/models/Pneumonia_model4_clahe.h5")
from tensorflow.keras.models import load_model
model=load_model("/content/drive/MyDrive/Research_workarea/xray_pneumonia/models/Pneumonia_model4_clahe.h5")

model.evaluate(X_test, to_categorical(np.array(y_test)))

#epsilon = 0.007


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.007]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.008


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.008]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.009


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.009]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.01


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.01]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))