# -*- coding: utf-8 -*-
"""Pneumonia_model4_11may_diffeps_better results_UM_Minimum_a4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vdXQSK0QZZixGYWwa4_t6GMZytarW35Y

https://towardsdatascience.com/hands-on-tutorial-for-applying-grad-cams-for-explaining-image-classifiers-using-keras-and-cbdcef68bb89
"""

import numpy as np # linear algebra
import cv2 # import cv2
from PIL import Image

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/Research_workarea/xray_pneumonia/xray_pneumonia.zip

train_folder = '/content/xray_pneumonia/train'
test_folder ='/content/xray_pneumonia/test'
val_folder ='/content/xray_pneumonia/val'

labels = ["NORMAL", "PNEUMONIA"] # each folder has two sub folder name "PNEUMONIA", "NORMAL"
IMG_SIZE = 224 # resize image

def get_data_train(data_dir):
    data = []

    for label in labels:
        count = 0
        path = os.path.join(data_dir, label)
        class_num = labels.index(label)
        for img in os.listdir(path):
            try:
                count = count + 1
                if(count > 1341):
                  break
                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                data.append([new_array, class_num])
            except Exception as e:
                print(e)
    return np.array(data)

import os
train = get_data_train(train_folder)
test = get_data_train(test_folder)
val = get_data_train(val_folder)

X_train = []
y_train = []

X_val = []
y_val = []

X_test = []
y_test = []

for feature, label in train:
    X_train.append(feature)
    y_train.append(label)

for feature, label in test:
    X_test.append(feature)
    y_test.append(label)

for feature, label in val:
    X_val.append(feature)
    y_val.append(label)

from scipy.ndimage import median
import imageio
import numpy as np
from scipy.ndimage.filters import gaussian_filter, median_filter, maximum_filter, minimum_filter
from skimage import img_as_float

radius = 5
amount = 4

for i in range(len(X_train)):
  image = X_train[i]/255# ensuring float values for computations
  blurred_image = minimum_filter(image, size=20)
  mask = image - blurred_image # keep the edges created by the filter
  sharpened_image = image + mask * amount
  sharpened_image = np.clip(sharpened_image, float(0), float(1)) # Interval [0.0, 1.0]
  X_train[i] = sharpened_image


for i in range(len(X_test)):
  image = X_test[i]/255# ensuring float values for computations
  blurred_image = minimum_filter(image, size =20)
  mask = image - blurred_image # keep the edges created by the filter
  sharpened_image = image + mask * amount
  sharpened_image = np.clip(sharpened_image, float(0), float(1)) # Interval [0.0, 1.0]
  X_test[i] = sharpened_image


for i in range(len(X_val)):
  image = X_val[i]/255# ensuring float values for computations
  blurred_image = minimum_filter(image, size = 20)
  mask = image - blurred_image # keep the edges created by the filter
  sharpened_image = image + mask * amount
  sharpened_image = np.clip(sharpened_image, float(0), float(1)) # Interval [0.0, 1.0]
  X_val[i] = sharpened_image

X_train = np.array(X_train).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_train = np.array(y_train)

X_val =np.array(X_val).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_val = np.array(y_val)

X_test = np.array(X_test).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_test = np.array(y_test)

import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.layers import Flatten, Conv2D, Activation, Dense, Dropout, MaxPooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

# model = Sequential()

# model.add(Conv2D(32, (3, 3), padding="same", input_shape=X_train.shape[1:]))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(2, 2))
# model.add(Dropout(0.2))

# model.add(Conv2D(64, (3, 3), padding="same"))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(2, 2))
# model.add(Dropout(0.4))

# model.add(Flatten())
# model.add(Dense(128, activation="relu"))
# model.add(Dense(64, activation="relu"))
# model.add(Dense(32, activation="relu"))
# model.add(Dense(2))
# model.add(Activation("sigmoid"))

# model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
# history = model.fit(X_train, to_categorical(np.array(y_train)), epochs=12, validation_data=(X_test, to_categorical(np.array(y_test))), shuffle=True)

# model.save('/content/drive/MyDrive/Research_workarea/xray_pneumonia/models/Pneumonia_model4_um_minimum1_a4.h5')

import keras

#model.save("Pneumonia_model4.h5")
from tensorflow.keras.models import load_model
model=load_model("/content/drive/MyDrive/Research_workarea/xray_pneumonia/models/Pneumonia_model4_um_minimum1_a4.h5")

y_pred = model.predict(X_test)

print(y_pred)

print(y_pred[0])
print(y_pred[0][1])

print(len(y_pred))

X_test_filtered=[]
y_test_original=[]
image_probs_orig=[]

count = 0
for i in range(len(y_pred)):
  if(y_pred[i][0]>=0.1 and y_pred[i][0]<=0.9 and count<130):
    print(i,":",y_pred[i])
    X_test_filtered.append(np.array(X_test[i]))
    y_test_original.append(y_test[i])
    image_probs_orig.append(y_pred[i])
    count = count + 1
print("count : ", count)

model.evaluate(X_test, to_categorical(np.array(y_test)))

print(y_test[234])

print(to_categorical(np.array(y_test)))

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

print(y_test[205])

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def argmax(array):
  index, value = 0, array[0]
  for i,v in enumerate(array):
    if v > value:
      index, value = i,v
  return index

model.summary()

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.001]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)

print(image_probs_orig)

print(image_probs_adv)

image_probs_adv[1][0]

image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

print(image_probs_adv1)

print(len(image_probs_orig))
print(len(image_probs_adv1))

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))
print(abspred)

np.sum(abspred,axis=0)

#epsilon = 0.002

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.002]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.003

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.003]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.004

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.004]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.005

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.005]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.006

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.006]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.007

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.007]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.008

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.008]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.009

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.009]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

#epsilon = 0.01

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def create_adversarial_pattern(input_image, input_label):
  with tf.GradientTape() as tape:
    tape.watch(input_image)
    prediction = model(input_image)
    #print("Prediction",prediction)
    #print("end prediction")
    loss = loss_object(input_label, prediction)
    #print("input label",input_label)
    #print("prediction",prediction)
    #print("loss",loss)
    #print(loss.shape)

  # Get the gradients of the loss w.r.t to the input image.
  gradient = tape.gradient(loss, input_image)
  #print("gradient",gradient)
  # Get the sign of the gradients to create the perturbation
  signed_grad = tf.sign(gradient)
  return signed_grad

def display_images(image, description):
  label=model.predict(image)
  image_probs_adv.append(label)
  plt.figure()
  plt.imshow(image[0]*0.5+0.5)
  plt.savefig('adversarial004.png')
  plt.title(label)
  plt.show()

for i in range(len(X_test_filtered)):
    data=np.array(X_test_filtered[i])
    data=data.reshape(-1,224,224,1)
    #print(model.predict(np.array(data)))
    image=np.array(data)
    image = tf.convert_to_tensor(image)
    #print("image",np.max(image))
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    image_probs = model.predict(image)
    image_probs=np.array(image_probs).flatten()
    #print("image probs:",image_probs)
    image_index = argmax(image_probs)
    #print("image index:",image_index)
    print("Original image with prediction: ")
    plt.figure()
    plt.title(image_probs)
    plt.imshow(X_test_filtered[i]*0.5+0.5)
    plt.show()
    y_test_filtered.append(image_index)
    label = tf.one_hot(image_index, image_probs.shape[-1])
    label = tf.reshape(label, (1, image_probs.shape[-1]))
    #print("label",label)
    #print("end label")
    #image=preprocess(image)
    #image= tf.squeeze(image,1)
    #print("im:", image.shape)
    perturbations = create_adversarial_pattern(image, label)
    epsilons=[0.01]
    descriptions = [('Epsilon = {:0.3f}'.format(eps) if eps else 'Input')
                for eps in epsilons]

    for i, eps in enumerate(epsilons):
      adv_x = image + eps*perturbations
      adv_x = tf.clip_by_value(adv_x, -1, 1)
      print("adversarial image with prediction: ")
      display_images(adv_x,descriptions[i])
    X_test_adversary.append(adv_x)


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))