# -*- coding: utf-8 -*-
"""Pneumonia_model4_11may_diffeps_better results_HFE_50_pgd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14x2ospD0yfAM1qHMJmziBsENoufaO1Cs

https://towardsdatascience.com/hands-on-tutorial-for-applying-grad-cams-for-explaining-image-classifiers-using-keras-and-cbdcef68bb89
"""

import numpy as np # linear algebra
import cv2 # import cv2
from PIL import Image

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/Research_workarea/xray_pneumonia/xray_pneumonia.zip

train_folder = '/content/xray_pneumonia/train'
test_folder ='/content/xray_pneumonia/test'
val_folder ='/content/xray_pneumonia/val'

labels = ["NORMAL", "PNEUMONIA"] # each folder has two sub folder name "PNEUMONIA", "NORMAL"
IMG_SIZE = 224 # resize image

def get_data_train(data_dir):
    data = []

    for label in labels:
        count = 0
        path = os.path.join(data_dir, label)
        class_num = labels.index(label)
        for img in os.listdir(path):
            try:
                count = count + 1
                if(count > 1341):
                  break
                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                data.append([new_array, class_num])
            except Exception as e:
                print(e)
    return np.array(data)

import os
train = get_data_train(train_folder)
test = get_data_train(test_folder)
val = get_data_train(val_folder)

X_train = []
y_train = []

X_val = []
y_val = []

X_test = []
y_test = []

for feature, label in train:
    X_train.append(feature)
    y_train.append(label)

for feature, label in test:
    X_test.append(feature)
    y_test.append(label)

for feature, label in val:
    X_val.append(feature)
    y_val.append(label)

import numpy as np
from scipy.fftpack import fft2, ifft2, fftshift
import imageio
from collections import OrderedDict, defaultdict

def to_grayscale(image):
	red_v = image[:, :, 0] * 0.299
	green_v = image[:, :, 1] * 0.587
	blue_v = image[:, :, 2] * 0.144
	image = red_v + green_v + blue_v

	return image.astype(np.uint8)

def normalize(min_old, max_old, min_new, max_new, val):
	'''Normalizes values to the interval [min_new, max_new]

	Parameters:
		min_old: min value from old base.
		max_old: max value from old base.
		min_new: min value from new base.
		max_new: max value from new base.
		val: float or array-like value to be normalized.
	'''

	ratio = (val - min_old) / (max_old - min_old)
	normalized = (max_new - min_new) * ratio + min_new
	return normalized.astype(np.uint8)

def histogram(data):
	'''Generates the histogram for the given data.

	Parameters:
		data: data to make the histogram.

	Returns: histogram, bins.
	'''

	pixels, count = np.unique(data, return_counts=True)
	hist = OrderedDict()

	for i in range(len(pixels)):
		hist[pixels[i]] = count[i]

	return np.array(list(hist.values())), np.array(list(hist.keys()))

d0v = 50

d=0
c=0

for d in range(len(X_train)):
  image = X_train[d]
  if len(image.shape) == 3:
      img_grayscale = to_grayscale(image)
  img = normalize(np.min(image), np.max(image), 0, 255, image)
  # HF part
  img_fft = fft2(img)  # img after fourier transformation
  img_sfft = fftshift(img_fft)  # img after shifting component to the center

  m, n = img_sfft.shape
  filter_array = np.zeros((m, n))

  for i in range(m):
      for j in range(n):
          filter_array[i, j] = 1.0 - np.exp(- ((i-m / 2.0) ** 2 + (j-n / 2.0) ** 2) / (2 * (d0v ** 2)))
  k1 = 0.5
  k2 = 0.75
  high_filter = k1 + k2*filter_array

  img_filtered = high_filter * img_sfft
  img_hef = np.real(ifft2(fftshift(img_filtered)))  # HFE filtering done

  # HE part
  # Building the histogram
  hist, bins = histogram(img_hef)
  # Calculating probability for each pixel
  pixel_probability = hist / hist.sum()
  # Calculating the CDF (Cumulative Distribution Function)
  cdf = np.cumsum(pixel_probability)
  cdf_normalized = cdf * 255
  hist_eq = {}
  for i in range(len(cdf)):
      hist_eq[bins[i]] = int(cdf_normalized[i])

  for i in range(m):
      for j in range(n):
          image[i][j] = hist_eq[img_hef[i][j]]
  X_train[d] = image

for c in range(len(X_test)):
  image = X_test[c]
  if len(image.shape) == 3:
      img_grayscale = to_grayscale(image)
  img = normalize(np.min(image), np.max(image), 0, 255, image)
  # HF part
  img_fft = fft2(img)  # img after fourier transformation
  img_sfft = fftshift(img_fft)  # img after shifting component to the center

  m, n = img_sfft.shape
  filter_array = np.zeros((m, n))

  for i in range(m):
      for j in range(n):
          filter_array[i, j] = 1.0 - np.exp(- ((i-m / 2.0) ** 2 + (j-n / 2.0) ** 2) / (2 * (d0v ** 2)))
  k1 = 0.5
  k2 = 0.75
  high_filter = k1 + k2*filter_array

  img_filtered = high_filter * img_sfft
  img_hef = np.real(ifft2(fftshift(img_filtered)))  # HFE filtering done

  # HE part
  # Building the histogram
  hist, bins = histogram(img_hef)
  # Calculating probability for each pixel
  pixel_probability = hist / hist.sum()
  # Calculating the CDF (Cumulative Distribution Function)
  cdf = np.cumsum(pixel_probability)
  cdf_normalized = cdf * 255
  hist_eq = {}
  for i in range(len(cdf)):
      hist_eq[bins[i]] = int(cdf_normalized[i])

  for i in range(m):
      for j in range(n):
          image[i][j] = hist_eq[img_hef[i][j]]
  X_test[c] = image

b=0
for b in range(len(X_val)):
  image = X_val[b]
  if len(image.shape) == 3:
      img_grayscale = to_grayscale(image)
  img = normalize(np.min(image), np.max(image), 0, 255, image)
  # HF part
  img_fft = fft2(img)  # img after fourier transformation
  img_sfft = fftshift(img_fft)  # img after shifting component to the center

  m, n = img_sfft.shape
  filter_array = np.zeros((m, n))

  for i in range(m):
      for j in range(n):
          filter_array[i, j] = 1.0 - np.exp(- ((i-m / 2.0) ** 2 + (j-n / 2.0) ** 2) / (2 * (d0v ** 2)))
  k1 = 0.5
  k2 = 0.75
  high_filter = k1 + k2*filter_array

  img_filtered = high_filter * img_sfft
  img_hef = np.real(ifft2(fftshift(img_filtered)))  # HFE filtering done

  # HE part
  # Building the histogram
  hist, bins = histogram(img_hef)
  # Calculating probability for each pixel
  pixel_probability = hist / hist.sum()
  # Calculating the CDF (Cumulative Distribution Function)
  cdf = np.cumsum(pixel_probability)
  cdf_normalized = cdf * 255
  hist_eq = {}
  for i in range(len(cdf)):
      hist_eq[bins[i]] = int(cdf_normalized[i])

  for i in range(m):
      for j in range(n):
          image[i][j] = hist_eq[img_hef[i][j]]
  print(b)
  X_val[b] = image

X_train = np.array(X_train) / 255
X_val = np.array(X_val) / 255
X_test = np.array(X_test) / 255

X_train = X_train.reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_train = np.array(y_train)

X_val = X_val.reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_val = np.array(y_val)

X_test = X_test.reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y_test = np.array(y_test)

import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.layers import Flatten, Conv2D, Activation, Dense, Dropout, MaxPooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

# model = Sequential()

# model.add(Conv2D(32, (3, 3), padding="same", input_shape=X_train.shape[1:]))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(2, 2))
# model.add(Dropout(0.2))

# model.add(Conv2D(64, (3, 3), padding="same"))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(2, 2))
# model.add(Dropout(0.4))

# model.add(Flatten())
# model.add(Dense(128, activation="relu"))
# model.add(Dense(64, activation="relu"))
# model.add(Dense(32, activation="relu"))
# model.add(Dense(2))
# model.add(Activation("sigmoid"))

# model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
# history = model.fit(X_train, to_categorical(np.array(y_train)), epochs=12, validation_data=(X_test, to_categorical(np.array(y_test))), shuffle=True)

# model.save('/content/drive/MyDrive/Research_workarea/xray_pneumonia/models/Pneumonia_model4_hfe.h5')

import keras

#model.save("Pneumonia_model4.h5")
from tensorflow.keras.models import load_model
model=load_model("/content/drive/MyDrive/Research_workarea/xray_pneumonia/models/Pneumonia_model4_hfe50.h5")

y_pred = model.predict(X_test)

print(y_pred)

print(y_pred[0])
print(y_pred[0][1])



print(len(y_pred))

X_test_filtered=[]
y_test_original=[]
image_probs_orig=[]

count = 0
for i in range(len(y_pred)):
  if(y_pred[i][0]>=0.1 and y_pred[i][0]<=0.9 and count<130):
    print(i,":",y_pred[i])
    X_test_filtered.append(np.array(X_test[i]))
    y_test_original.append(y_test[i])
    image_probs_orig.append(y_pred[i])
    count = count + 1
print("count : ", count)



model.evaluate(X_test, to_categorical(np.array(y_test)))

print(y_test[234])

print(to_categorical(np.array(y_test)))

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

print(y_test[205])

image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

def argmax(array):
  index, value = 0, array[0]
  for i,v in enumerate(array):
    if v > value:
      index, value = i,v
  return index

model.summary()

iterations = 7
alpha = 2

epsilon = 1/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,1)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,1)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

epsilon = 2/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,1)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,1)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

epsilon = 3/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,1)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,1)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

epsilon = 4/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,1)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,1)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))

epsilon = 5/255


image_probs_adv=[]
y_test_filtered=[]
X_test_adversary=[]

image_count = 0
flag = 0
orig_label = []
for i in range(len(X_test_filtered)):
  gen_img = tf.identity(X_test_filtered[i])
  gen_img = gen_img + tf.random.uniform(gen_img.get_shape().as_list(), minval=-epsilon, maxval=epsilon, dtype=tf.dtypes.double)
  x_temp = X_test_filtered[i]
  imgv = tf.Variable(gen_img)
  img=np.array(imgv)
  img=img.reshape(1,224,224,1)
  imgv = tf.convert_to_tensor(img)
  #print(img)
  image_probs = model.predict(img)
  image_probs=np.array(image_probs).flatten()
  #print("image probs:",image_probs)
  image_index = argmax(image_probs)
  y_test_filtered.append(image_index)
  plt.figure()
  plt.title(image_probs)
  plt.imshow(X_test_filtered[i]*0.5+0.5)
  plt.show()
  print(i," : ",image_index)

  with tf.GradientTape() as tape:
    tape.watch(imgv)
    predictions = model(imgv)
    label = tf.one_hot(image_index, predictions.shape[-1])
    label = tf.reshape(label, (1, predictions.shape[-1]))
    print("label",label)
    print("predictions",predictions)
    loss_object = tf.keras.losses.CategoricalCrossentropy()
    loss = loss_object(label, predictions)
    #print("loss",loss)
    #print("y_test",y_test)

    #print("imgv",imgv)
  grads = tape.gradient(loss,imgv)
  #print(grads)
  signed_grads = tf.sign(grads)
  gen_img = gen_img + (alpha*signed_grads)
  gen_img = tf.clip_by_value(gen_img, X_test_filtered[i]-epsilon, X_test_filtered[i]+epsilon)
  orig_label.append(y_test_filtered[i])
  #gen_image = gen_img.numpy()*255
  #orig_image = imgv.numpy()*255

  gen_image = gen_img.numpy()
  orig_image = imgv.numpy()
  predictions_gen = model(gen_image)
  image_probs_adv.append(predictions_gen)
  predictions_gen=np.array(predictions_gen).flatten()
  gen_image=gen_image.reshape(224,224,1)
  plt.figure()
  plt.title(predictions_gen)
  plt.imshow(gen_image*0.5+0.5)
  plt.show()

  X_test_adversary.append(gen_image)
  #print(orig_image)
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_gen_img.png',np.clip(gen_image, 0, 255).astype('uint8'))
  cv2.imwrite('/content/pgd_cifar10/'+str(image_count)+'_orig_img.png',np.clip(orig_image, 0, 255).astype('uint8'))


image_probs_adv1 = []
for i in range(len(image_probs_adv)):
  image_probs_adv1.append(image_probs_adv[i][0])

abspred=(abs(np.subtract(np.array(image_probs_orig),np.array(image_probs_adv1))))

print(np.sum(abspred,axis=0))